#!/bin/bash

#Author: Shwet Raj
#Date: 20/10/20
#Description: Script to backup /etc and /var filesystem into backup.tar.gz.
#Modified: 20/10/20

tar cvf /home/shwetraj/backup.tar /etc /var
gzip /home/shwetraj/backup.tar

find /home/shwetraj/backup.tar.gz -mtime -1 -type f -print &> /dev/null

if [ $? -eq 0 ]

then 
    echo Backup successfully created!
    echo
    echo Archiving backup..

#scp /tmp/backup.tar.gz root@192.168.1.x:/path

else
echo Backup failed.

fi
