#!/bin/bash

# Author: Shwet Raj
# Date: 23/10/20
# Description: This script will log only defined keywords
# Modified: 23/10/20

tail -fn0 /var/log/messages | while read line
do


    echo $line | egrep -i "refused|invalid|error|fail|lost|shut|down|offline"

    if [ $? = 0 ]
 
    then
 
    echo $line >> /tmp/filtered-messages

    fi

done
