#!/bin/bash

# Author: Shwet Raj
# Date: 21/10/20
# Description: Script to check the directories in /home are assigned to a user or not
# Modified: 21/10/20

cd /home
for DIR in *

do 

    CHK=$(grep -c "/home/$DIR" /etc/passwd)

    if [ $CHK -ge 1 ]

    then
 
    echo "$DIR is assigned to a user"
    
    else
  
    echo "$DIR is NOT assigned to a user"

    fi

done
