#!/bin/bash

# Author: Shwet Raj
# Date: 23/10/20
# Description: This Script will create new user and error out if user exist.
# Modified: 23/10/20

echo "Please provide a username?"
read u
echo

grep -q $u /etc/passwd
        if [ $? -eq 0 ]
        then
        echo ERROR -- USER $u already exist
        echo Please choose another username
        echo
        exit 0
        fi

useradd $u
echo $u account has been created


