#!/bin/bash

# Author: Shwet Raj
# Date: 25/10/2020
# Description: This script will disable the user who has not been logged in a while.
# Modified: 25/10/2020

a=`lastlog -b 90 | tail -n+2 | grep 'Roy' | awk '{print $1}'`

for i in $a
do
 
  usermod -L $i
done
