#!/bin/bash

# Author: Shwet Raj
# Date: 22/10/20
# Description: This script is used to find out the number users login.
# Modified: 22/10/20

echo "Please enter day (e.g. Mon)"
read d
echo
echo "Please enter month (e.g. Aug)"
read m
echo
echo "Please enter date (e.g. 28)"
read da
last | grep "$d $m $da" | awk '{print $1}'
#last | grep "$d $m $da"
