#!/bin/bash

#Author: Shwet Raj
#Date: 15/10/2020
#Description: This script is used to pull error form /var/log/message directory.
#Modified: 15/10/2020


grep -i error /home/shwetraj/Real-Life-Scripts/messages
